### ISSUE TITLE
Failed to call deck during gpml compiling

### ISSUE THREAD

**Issue by jingwei-li** [jhadida/gpso#2]
Hi, I was using your GPSO and Deck packages long time ago and it worked very well. Now when I want to replicate my previous results. I found gpso cannot recognize deck (dk.xxx) even though I added path for both packages.

So I tried to remove the previous repositories and reinstall everything.
First I followed this readme https://github.com/jhadida/deck to install deck and it was successful. See the following screenshots:
![image](https://user-images.githubusercontent.com/19770389/63992213-6cb80480-cb1d-11e9-8b43-b6760f4118a7.png)
![image](https://user-images.githubusercontent.com/19770389/63992152-2793d280-cb1d-11e9-9849-1c02f64dd523.png)
![image](https://user-images.githubusercontent.com/19770389/63992172-3f6b5680-cb1d-11e9-81db-022a156ae60a.png)

Then I followed the gpso readme: https://github.com/jhadida/gpso. But when I run gpml_start, it said it cannot find deck:
![image](https://user-images.githubusercontent.com/19770389/63992260-9c670c80-cb1d-11e9-94dc-51c1e1181358.png)
As you can see, the deck paths and gpso paths are already inside matlab paths.

How should I fix this problem? Thanks in advance.

**Comment by jhadida** [comment]
Hi @jingwei-li 

Apologies, I made a few changes to Deck yesteday, and forgot to merge them into the master branch. Pulling the latest version of Deck should fix your issue. Please let me know how it goes so I can close this issue :)

**Comment by jingwei-li** [comment]
Thanks. It works now! :D
